### ISSUE TITLE
Add "last updated on"

### ISSUE THREAD

**Issue by Alterrien** [rb28z2/progress-bot#3]
Hey,
I Thought it could be nice to keep track of when has the tracker has been uploaded last, what do you think about it ? I can implement it, if you want.
Cheers !

**Comment by rb28z2** [comment]
I really like this idea! Absolutely go ahead and implement it and send a pull request. I'll be happy to merge it in.

Just a few things I'd prefer you keep in mind: keep the last updated unintrusive so it doesn't draw attention to itself but is still easily visible when required. Kind of like the link to GitHub I have on there currently. So I'm thinking somewhere along the edges would be perfect.

Feel free to ask if you need anything from me.

**Comment by Alterrien** [comment]
Alright, i'll get to it tomorrow !
