### ISSUE TITLE
DOM gets duplicated when the page is left open for a long time

### ISSUE THREAD

**Issue by IntermittentlyRupert** [rb28z2/progress-bot#36]
**Browser:** Firefox, currently v74.0 but has been happening for a while (might affect other browsers, but I haven't tested)

If I leave the [asenshi.moe](https://asenshi.moe) landing page open for a long time, the progress widget duplicates several of the progress bars. This takes anywhere between a couple of hours and overnight - the exact amount of time varies.

<img width="182" alt="page" src="https://user-images.githubusercontent.com/4526480/78964414-6a9b3700-7b3d-11ea-859c-fe5a2940d4e2.PNG">

This appears to be associated with the actual child nodes of the `.pb-div` elements being duplicated, i.e. there is an `svg` node, then a `div.progressbar-text` node, then a second `svg` node and a second `div.progressbar-text` node for that progress bar. No errors are logged to the console when this issue occurs.

Additionally, for progress bars that have alternate hover text, an additional copy of the non-hover text gets added each time you hover over the bar. The text is duplicated in both instances of the `div.progressbar-text` DOM node.

Here's a paste of the iframe DOM for the above screenshot: [https://pastebin.com/tnK0ZDr0](https://pastebin.com/tnK0ZDr0)

**Comment by IntermittentlyRupert** [comment]
Just looked into it a little and this seems to happen whenever the websocket reconnects after a connection drop. This is because `assets/updater_functions.js` assumes that `init-stats` will be sent exactly once per page-load.

I'll submit a pull request.

**Comment by IntermittentlyRupert** [comment]
Detailed reproduction steps:

1. Run the server on one computer and load the web page in a browser on a different computer connected to the same network.
    - This also will work for the production https://asenshi.moe:8443 and any web browser.
2. Disconnect one of the two computers from the network.
3. Reconnect to the network.

After a few seconds, the `init-stats` message will be sent and duplicate `ProgressBar.Line`s will be created.

**Comment by rb28z2** [comment]
PR #37 fixes this
