### ISSUE TITLE
Slow loading on Firefox 78.0.2

### ISSUE THREAD

**Issue by Adamantcheese** [rb28z2/progress-bot#46]
While the widget does eventually load, it seems to take almost exactly 30 seconds to load on Firefox when in Google or Chrome it loads instantly. Not sure if there's anything you can do to remedy that or if it's a Firefox issue, which I suspect it is.

**Comment by rb28z2** [comment]
Sounds like something might be timing out. Are you able to provide console logs while the page is trying to load?

**Comment by Adamantcheese** [comment]
Here's everything that the console spits out; note that the "Brand New Animal" and "12/12" lines appear exactly as the graphics load in, which again, is almost exactly 30 seconds after that red error block. (Updated image with better info)
![image](https://user-images.githubusercontent.com/9031585/88620605-4c593880-d053-11ea-8b5f-2b48dfc3d0ea.png)

**Comment by rb28z2** [comment]
Hmm yeah I was able to reproduce this on FF as well. It seems to be hanging on the load of progressbar.min.js for some reason. I'm not sure why this is, so it may take some time for me to figure it out and push out a fix. I may be able to work around it by using a CDN to load that specific file over serving it locally but its something I'll have to explore.

Honestly this is going to be fairly low priority as I'm more interested in rewriting this whole project as its been long overdue.

**Comment by Adamantcheese** [comment]
I wonder if it would be as simple as moving the script declarations around so that progressbar.min.js comes before updater_functions.js in the HTML so that it's loaded before any updates occur?

**Comment by rb28z2** [comment]
Hmmm that's a good idea and certainly worth trying.

**Comment by rb28z2** [comment]
@Adamantcheese I've made the changes and updated the version that's running on the website. It seems to load correctly on FF for me now - please take a look and let me know if the issue persists.

**Comment by Adamantcheese** [comment]
Working correctly now for me! Thanks for the update!
